# Generated by Django 4.0.5 on 2022-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_branch_contact_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='category.contact'),
        ),
    ]
