# Generated by Django 4.0.5 on 2022-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_course_branches_course_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(blank=True, to='category.branch'),
        ),
    ]
