# Generated by Django 4.0.5 on 2022-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='car_type',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Cargo', 'Cargo'), ('Electo', 'Electro')], max_length=30),
        ),
    ]
