# Generated by Django 4.0.5 on 2022-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_category_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='imgpath',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='d', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
